name: Say hello

on:
  push:
    branches:
    - Devs
    - Release

jobs:
  Hola:
    runs-on:  ubuntu-18.04
    steps:
      - name : Echo the message 
        run: |
            echo "Hola midu!"
        # .\SsTaimsal2023\SsTaimsal2023
